<#
.SYNOPSIS
    Builds CameraInternet-Setup.cmd - a single self-contained installer file.

.DESCRIPTION
    The generated .cmd carries the whole application (CameraInternet.ps1, the
    launcher, the shortcut installer and the README) as base64 payload. Running
    it unpacks everything to %LOCALAPPDATA%\Programs\CameraInternet and creates
    the "Camera Internet" shortcuts.

    Re-run this script after changing any of the source files, otherwise the
    setup file keeps shipping the previous version.

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File .\Build-Setup.ps1
#>
[CmdletBinding()]
param(
    [string]$OutputPath = (Join-Path $PSScriptRoot 'CameraInternet-Setup.cmd')
)

$ErrorActionPreference = 'Stop'

$payloadFiles = @(
    'CameraInternet.ps1',
    'Start-CameraInternet.cmd',
    'Install-CameraInternet.ps1',
    'README.md'
)

function ConvertTo-PayloadBlock {
    param([string]$Name, [string]$Path)
    $bytes  = [System.IO.File]::ReadAllBytes($Path)
    $base64 = [Convert]::ToBase64String($bytes)
    $lines  = New-Object System.Collections.ArrayList
    for ($i = 0; $i -lt $base64.Length; $i += 200) {
        $length = [Math]::Min(200, $base64.Length - $i)
        [void]$lines.Add($base64.Substring($i, $length))
    }
    $builder = New-Object System.Text.StringBuilder
    [void]$builder.AppendLine(("`$Payload['{0}'] = @'" -f $Name))
    foreach ($line in $lines) { [void]$builder.AppendLine($line) }
    [void]$builder.AppendLine("'@")
    return $builder.ToString()
}

$blocks = New-Object System.Text.StringBuilder
foreach ($name in $payloadFiles) {
    $path = Join-Path $PSScriptRoot $name
    if (-not (Test-Path -LiteralPath $path)) { throw "Missing source file: $path" }
    [void]$blocks.AppendLine((ConvertTo-PayloadBlock -Name $name -Path $path))
}

# The batch header runs first; cmd stops at "goto :eof", so the PowerShell
# payload below the marker is never parsed by the command interpreter. The
# marker is written in two halves here so that it occurs exactly once in the
# generated file.
$header = @'
@echo off
rem ===========================================================================
rem  Camera Internet - self-contained setup
rem
rem  Unpacks the application to %LOCALAPPDATA%\Programs\CameraInternet and
rem  creates the "Camera Internet" shortcuts. No administrator rights are
rem  needed to install; the application itself asks for them when it starts.
rem
rem  Usage:  CameraInternet-Setup.cmd              install
rem          CameraInternet-Setup.cmd /uninstall   remove the shortcuts and files
rem
rem  Generated by Build-Setup.ps1 - do not edit by hand.
rem ===========================================================================
title Camera Internet Setup
setlocal
set "CAMERAINTERNET_SETUP_ARGS=%*"
powershell.exe -NoLogo -NoProfile -ExecutionPolicy Bypass -Command "$t = Get-Content -LiteralPath '%~f0' -Raw; $m = ':::CAMERA' + 'INTERNET:::'; $i = $t.IndexOf($m); if ($i -lt 0) { Write-Host 'This setup file is damaged.' -ForegroundColor Red; exit 1 }; Invoke-Expression $t.Substring($i + $m.Length)"
echo.
pause
endlocal
goto :eof
:::CAMERAINTERNET:::
'@

$installer = @'
$ErrorActionPreference = 'Stop'

$AppName     = 'Camera Internet'
$TargetDir   = Join-Path $env:LOCALAPPDATA 'Programs\CameraInternet'
$DataDir     = Join-Path $env:LOCALAPPDATA 'CameraInternet'
$IconPath    = Join-Path $DataDir 'CameraInternet.ico'
$LinkName    = 'Camera Internet.lnk'
$DesktopLink = Join-Path ([System.Environment]::GetFolderPath('Desktop')) $LinkName
$StartDir    = Join-Path ([System.Environment]::GetFolderPath('Programs')) 'Camera Internet'
$StartLink   = Join-Path $StartDir $LinkName
$Payload     = @{}

__PAYLOAD__

function Set-RunAsAdministratorFlag {
    # Byte 0x15 of a .lnk holds the extra flags; 0x20 is the "run elevated" bit.
    param([string]$Path)
    try {
        $bytes = [System.IO.File]::ReadAllBytes($Path)
        if ($bytes.Length -gt 0x15) {
            $bytes[0x15] = $bytes[0x15] -bor 0x20
            [System.IO.File]::WriteAllBytes($Path, $bytes)
        }
    } catch {
        Write-Host ("  note: the shortcut could not be marked 'run as administrator' ({0})" -f $_.Exception.Message) -ForegroundColor Yellow
    }
}

function New-AppShortcut {
    param([string]$Path, [string]$Icon)
    $shell = New-Object -ComObject WScript.Shell
    try {
        $link = $shell.CreateShortcut($Path)
        $link.TargetPath       = Join-Path $PSHOME 'powershell.exe'
        $link.Arguments        = '-STA -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -WindowStyle Hidden -File "{0}"' -f (Join-Path $TargetDir 'CameraInternet.ps1')
        $link.WorkingDirectory = $TargetDir
        $link.Description      = 'Switch Internet sharing to the camera network on and off'
        $link.WindowStyle      = 7
        $link.IconLocation     = $Icon
        $link.Save()
    } finally {
        [void][System.Runtime.InteropServices.Marshal]::ReleaseComObject($shell)
    }
    Set-RunAsAdministratorFlag -Path $Path
}

function Invoke-Uninstall {
    Write-Host "Removing $AppName ..." -ForegroundColor Cyan
    foreach ($link in @($DesktopLink, $StartLink)) {
        if (Test-Path -LiteralPath $link) {
            Remove-Item -LiteralPath $link -Force -ErrorAction SilentlyContinue
            Write-Host "  removed $link"
        }
    }
    if ((Test-Path -LiteralPath $StartDir) -and -not (Get-ChildItem -LiteralPath $StartDir -Force)) {
        Remove-Item -LiteralPath $StartDir -Force -ErrorAction SilentlyContinue
    }
    if (Test-Path -LiteralPath $TargetDir) {
        Remove-Item -LiteralPath $TargetDir -Recurse -Force -ErrorAction SilentlyContinue
        Write-Host "  removed $TargetDir"
    }
    Write-Host ''
    Write-Host 'Done. The saved adapter selection and the log file were kept in:' -ForegroundColor Green
    Write-Host "  $DataDir"
    Write-Host 'Internet Connection Sharing itself was not changed. Switch it off in the'
    Write-Host 'application before uninstalling if it is still active.'
}

function Invoke-Install {
    Write-Host "Installing $AppName" -ForegroundColor Cyan
    Write-Host "  target folder: $TargetDir"
    Write-Host ''

    New-Item -ItemType Directory -Path $TargetDir -Force | Out-Null
    New-Item -ItemType Directory -Path $DataDir   -Force | Out-Null

    foreach ($name in @($Payload.Keys | Sort-Object)) {
        $bytes = [Convert]::FromBase64String(($Payload[$name] -replace '\s', ''))
        [System.IO.File]::WriteAllBytes((Join-Path $TargetDir $name), $bytes)
        Write-Host ("  unpacked {0} ({1:N0} bytes)" -f $name, $bytes.Length)
    }

    # Files unpacked from a downloaded setup can carry the "mark of the web".
    Get-ChildItem -LiteralPath $TargetDir -File | Unblock-File -ErrorAction SilentlyContinue

    $icon = Join-Path $env:SystemRoot 'System32\shell32.dll,17'
    try {
        & (Join-Path $PSHOME 'powershell.exe') -NoLogo -NoProfile -ExecutionPolicy Bypass `
            -File (Join-Path $TargetDir 'CameraInternet.ps1') -ExportIcon $IconPath | Out-Null
        if (Test-Path -LiteralPath $IconPath) { $icon = "$IconPath,0" }
    } catch {
        Write-Host '  note: using a stock Windows icon (the icon could not be generated)' -ForegroundColor Yellow
    }

    New-AppShortcut -Path $DesktopLink -Icon $icon
    Write-Host "  created $DesktopLink"

    New-Item -ItemType Directory -Path $StartDir -Force | Out-Null
    New-AppShortcut -Path $StartLink -Icon $icon
    Write-Host "  created $StartLink"

    Write-Host ''
    Write-Host 'Installed.' -ForegroundColor Green
    Write-Host 'Start it from the "Camera Internet" desktop shortcut. Windows asks for'
    Write-Host 'administrator confirmation (UAC) every time, because changing Internet'
    Write-Host 'Connection Sharing requires it.'
    Write-Host ''
    Write-Host "Log file:       $DataDir\CameraInternet.log"
    Write-Host "Documentation:  $TargetDir\README.md"

    $answer = Read-Host 'Start Camera Internet now? [y/N]'
    if ($answer -match '^(y|yes)$') {
        Start-Process -FilePath $DesktopLink
    }
}

try {
    $arguments = [string]$env:CAMERAINTERNET_SETUP_ARGS
    if ($arguments -match '(?i)(/|-{1,2})uninstall') {
        Invoke-Uninstall
    } else {
        Invoke-Install
    }
} catch {
    Write-Host ''
    Write-Host ('Setup failed: ' + $_.Exception.Message) -ForegroundColor Red
    Write-Host 'Nothing outside your user profile was changed.'
    exit 1
}
'@

$installer = $installer.Replace('__PAYLOAD__', $blocks.ToString().TrimEnd())
$content   = ($header + "`r`n" + $installer) -replace "`r`n|`r|`n", "`r`n"
[System.IO.File]::WriteAllText($OutputPath, $content, (New-Object System.Text.ASCIIEncoding))

$size = (Get-Item -LiteralPath $OutputPath).Length
Write-Host ("Built {0} ({1:N0} bytes) from {2} source files." -f $OutputPath, $size, $payloadFiles.Count)
